### ISSUE TITLE
Warning with Python 3.6 or newer

### ISSUE THREAD

**Issue by Fuzzy2319** [MonsterDruide1/OdysseyDecomp#129]
I recently updated my dev environment with ubuntu 24.04LTS and now I got warning every time I run `tools/check -mw3 <func>` or `tools/check-format.py`.
I search for this specific error and found this https://stackoverflow.com/questions/50504500/deprecationwarning-invalid-escape-sequence-what-to-use-instead-of-d 

![image](https://github.com/user-attachments/assets/11921527-2967-414f-a304-793f897194d3)
![image](https://github.com/user-attachments/assets/5374c9b0-a031-470c-a3c2-74e665c4ad55)

**Comment by LynxDev2** [comment]
Both work fine for me on Python 3.10.12

**Comment by MonsterDruide1** [comment]
I guess this should've said `Python 3.12`, because that one got newly introduced in `24.04` - `Python 3.6` is out since 2018, and `Python 3.16` does not even have a release schedule yet.

**Comment by MonsterDruide1** [comment]
Ah, now I get it - we were depending on a feature that got deprecated in `3.6`, but was still "fine" to use. Now, they replaced that deprecation warning with a full syntax error in `3.12`, so we need to fix it.
